In [1]:
from datasets import load_dataset
import re
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from transformers import T5Tokenizer , T5ForConditionalGeneration
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize
from transformers import DataCollatorForSeq2Seq, Trainer, TrainingArguments

d:\GitUploads\Case-Classification\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lalit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\lalit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [2]:
ds = load_dataset("ninadn/indian-legal")

In [3]:
ds

DatasetDict({
    train: Dataset({
        features: ['Text', 'Summary'],
        num_rows: 7030
    })
    test: Dataset({
        features: ['Text', 'Summary'],
        num_rows: 100
    })
})

In [4]:
train_df = ds['train'].to_pandas()
test_df = ds['test'].to_pandas()

In [5]:
train_df

,Text,Summary
0,Appeal No. LXVI of 1949.\nAppeal from the High...,The charge created in respect of municipal pro...
1,Civil Appeal No.94 of 1949.\n107 834 Appeal fr...,"An agreement for a lease, which a lease is by ..."
2,"iminal Appeal No. 40 of 1951, 127 Appeal from ...","The question whether a Magistrate is ""personal..."
3,Appeal No. 388 of 1960.\nAppeal by special lea...,The appellant was a member of a joint Hindu fa...
4,Appeal No. 198 of 1954.\nAppeal from the judgm...,The appellant was the Ruler of the State of Ba...
...,...,...
7025,Appeal No. 761 of 1957.\nAppeal by special lea...,The respondent company purchased certain machi...
7026,Appeal No. 761 of 1957.\nAppeal by special lea...,The respondent company purchased certain machi...
7027,Appeal No. 53 of 1958.\nAppeal by special leav...,"While this appeal by special leave, relating t..."
7028,Appeal No. 4 of 1960.\nAppeal by special leave...,The Punjab Government issued notification unde...
7029,Appeal No. 337 of 1960.\nAppeal by special lea...,The respondent who was a District and Sessions...

In [6]:
print(train_df['Summary'].value_counts().head(10))

Summary
The respondents filed a suit for specific performance against the appellant which was dismissed on March 12, 1954.\nOn March 24 the respondents made an application for a certified copy of the judgment and decree.\nThe decree was not drawn up and the respondents were supplied a certified copy of the judgment and the memo of costs.\nThe respondents filed an appeal before the High Court without the certified copy of the decree and only with the certified copy of the judgment and the memo of costs.\nThe appeal was admitted under 0.\n41, r. 11 Code of Civil Procedure on August 30, 1954.\nOn December 23, 1958, the appellant served a notice on the respondents that he would raise a preliminary objection at the hearing that the appeal was incompetent as a certified copy of the decree was not filed as required by 0. 41, r. 1.\nOn December 24, 1958, the respondents moved the trial Court for drawing up of the decree, but since the record was in the High Court this could not be done.\nAt the hearing of the appeal, the appellant raised the preliminary objection, but the High Court passed an order on December 15, 1959, allowing the respondents one month 's time for getting a decree drawn up and obtaining.\na copy and directed the record to be sent to the trial Court.\nAgainst this order the appellant preferred an appeal to the Supreme Court contending that the High Court was bound to dismiss the appeal as it was manifestly incompetent under 0.\n41, r. 1.\nSubsequently, on December 23, 1959, the respondents obtained a certified copy of the decree and filed it before the High Court the same day.\nThe appellant contended that the appeal was to be deemed to be filed on this date and was time barred.\nHeld, that in the circumstances of this case the order passed by the High Court was right. ' There was no doubt that 0. 41, r. 1 was mandatory and in the absence of or the decree the filing of the appeal was incomplete, defective and incompetent.\nThe office of the trial Court was negligent in not drawing up a decree and the office of the High Court was also not as careful as it should have been in examining the appeal and these have contributed substantially to the unfortunate position.\nIn such a case, the respondents deserved to be protected.\nBesides the, 919 question had become academic and technical in view of subse quent events.\nThe certified copy of the decree was filed on December 23, 1959, and even if the appeal was considered to have been filed on that date, it was within time.\nUnder section 12(2) of the Limitation Act the respondents could treat the time taken in the drawing up of the decree after the application for a certified copy thereof had been made as part of the time taken in obtaining the certified copy of the decree.\nTarabati Koer vs Lala jagdeo Narain, , Bani Madhub Mitter vs Matungini Desai, Cal.\n104 (F.B.), Gabriel Christian vs 'Chandra Mohan Missir, Pat. 284(F.B.), Jayashankar Mulshankar Mehta vs Mayabhai Lalbhai Shah, , Gokul Prasad vs Kunwar Bahadur, Luck.\n250 and Umda vs Rupchand, , referred to.\nRodger vs Comptoir d 'Escompte de Paris, (1871) L.R. 3 P.C. 465, relied on.\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   2
The respondent was posted as officer incharge of a police station when complaints were received by the District Magis trate that the respondent was receiving bribes.\nThe District Magistrate got an enquiry made by the Sub Divisional Magistrate and forwarded the report toghether with his own endorsement to the Superintendent of Police.\nThe respondent was forced to go on 2 months leave and was reverted to his substantive post of Head Constable, but later he was promoted to the rank of officiating Sub Inspector and posted at another police station.\nMeanwhile on further complaints an investigation was made and it was reported that the respondent was a habitual bribe taker.\nHe was charged under section 7 Police Act for 9 charges of bribery and after departmental trial was dismissed by the Superintendent of Police.\nHe filed a Writ Petition before the High court challenging the order of dismissal inter alia on the ground that the offences charged being cognizable offences the Superintendent of Police had no jurisdiction to hold the departmental trial without first complying with the provisions of para.\n486(1) of the U. P. Police Regulations.\nThe High Court accepted this contention and quashed the order of dismissal.\n673 Held (per Sarkar, Subba Rao and Mudholkar, JJ.) that the subject matter of the magisterial enquiry and of the depart mental trial was substantially the same and that the depart 'I mental trial was validly held.\nThe fact that there was an interregnum between the magisterial enquiry and the departmental trial did not affect the question.\nParagraph 486 did not apply to a case where a magisterial enquiry was ordered and a police officer could be departmentally tried under section 7 Police Act after such magisterial enquiry.\nPer Gajendragadkar and Wanchoo, JJ.\nThe provisions of para.\n486 were merely directory and even if there was non compliance therewith the order of dismissal was not invalidated.\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2
The business of the respondent club was to run race meetings on a commercial scale.\nThe club did not own any horse, and therefore did not employ jockeys.\nit was a matter of some importance to the club that there were jockeys of requisite skill and experience in sufficient numbers who would be available to the owners and trainers because otherwise the running of the race meetings would not be commercially profitable and its interest would suffer and it might have had to abandon its business if it did not take steps to make jockeys of the necessary calibre available.\nTherefore it established a school for the training of Indian boys as jockeys and claimed the sums spent on the running of the school as deductable amount under section 10 (2)(XV) of the Indian Income Tax Act.\nThe question was whether in the circumstances of the case the expenditure claimed was one which was wholly and exclusively laid out for the purpose of the respondent 's business.\nHeld, that any expenditure which was incurred for preventing the extinction of a business would be expenditure wholly and exclusively laid opt for the purpose of the business of the assessee and would be an allowable deduction.\nIn the instant case the amount in dispute was laid out wholly and exclusively for the purpose of the respondent 's business, because if the supply of jockeys of requisite efficiency and skill failed, the business of the respondent would no longer be possible.\nEastern Investments Ltd. vs Commissioner of Income tax, West Bengal, ; and Commissioner of Income tax vs Chandulal Keshavlal & Co., ; relied on, British Insulated and Helsby Cables vs Atherton, [1926] A. C. 205, Morgan vs Tate & Lyle Ltd., and Boarland vs Kramat Pulai Ltd., , discussed.\nStrong & Co. vs Woodifield, ; and Smith vs Incorporated Council of Law Reporting, , referred to.\nWard & Co. Ltd. vs Commissioner of Taxes, [1923] A. C. 145, distinguished.\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         2
The appellant who was carrying on business in food grains in partnership with another person submitted the returns of the income of the firm for the accounting years even after his partner 's death.\nIt was found that certain income of the firm was concealed and the Income tax Officer not only assessed the firm to tax for the suppressed income but also imposed penalties for concealing the said income.\nAppeals to the higher income tax authorities failed and the appellant then applied to the High Court for a writ of certiorari quashing the orders of assessment and imposition of penalty on the ground inter alia that the firm was dissolved by his partner 's death and no penalty could be imposed after dissolution of the firm, The High Court rejected the petition.\nOn appeal with the certificate of the High Court, Held, that by virtue of section 44 and other provisions of the Income Tax Act a partner of a dissolved partnership firm may not only be made liable to assessment for income tax for the accounting years but despite dissolution of the firm he may be made liable to pay penalty for concealing the income of the firm under section 28(1)(c) of the Act.\nThe analogy of dissolution of a Hindu joint Family does not apply to dissolution of a partnership.\nMareddi Krishna Reddy vs Income tax Officer, Tenali, , approved.\nCommissioner of Income tax vs Ravalaseema Oil Mills, and section V. Veerappan Chettiar vs Commissioner of Income tax, Madras, , disapproved.\nMahankali Subbarao vs Commissioner of Income tax, , distinguished.\nThe Legislature intended that the provisions of Ch.\nIV of the Act shall apply to a firm even after discontinuance of its business.\nIn interpreting a fiscal statute the Court cannot proceed to make good deficiencies if there be any.\nIn case of doubt it should be interpreted in favour of the tax payer.\nThe expression "assessment" has different connotations an has been used in its widest connotation in Ch.\nIV and section 44 97 766 he Act.\nIt is not restricted only to computation of tax but includes imposition of penalty on tax payers found in the process of assessment guilty of concealing income.\nCommissioner of Income tax, Bombay Presidency and Aden vs Khemchand Ramdas, , referred to.\nThe Income tax Act provided a complete machinery for obtaining relief against improper orders passed by the Income tax Authorities and the appellant could not be permitted to abandon that machinery, and invoke the jurisdiction of the High Court under article 226 of the Constitution against the orders of the taxing authorities.\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       2

In [7]:
stop_words = set(stopwords.words('english'))

In [8]:
def clean(text):
    if text is None:
        return ''
    text = re.sub(r'\d+','',text)
    text = re.sub(r'\n',' ',text)
    text = re.sub(r'\s+',' ',text)
    text = re.sub(r'[^\w\s]','',text)
    text = text.lower()
    text = ' '.join(word for word in text.split() if word not in stop_words)
    return text.strip()

In [9]:
train_df['Text'] = train_df['Text'].apply(clean)
train_df['Summary'] = train_df['Summary'].apply(clean)
test_df['Text'] = test_df['Text'].apply(clean)
test_df['Summary'] = test_df['Summary'].apply(clean)

In [10]:
train_df

,Text,Summary
0,appeal lxvi appeal high court judicature bomba...,charge created respect municipal property tax ...
1,civil appeal appeal judgment decree high court...,agreement lease lease indian declared include ...
2,iminal appeal appeal judgment order dated st j...,question whether magistrate personally interes...
3,appeal appeal special leave judgment order dat...,appellant member joint hindu family carried bu...
4,appeal appeal judgment order dated october for...,appellant ruler state baster later integrated ...
...,...,...
7025,appeal appeal special leave judgment order dat...,respondent company purchased certain machinery...
7026,appeal appeal special leave judgment order dat...,respondent company purchased certain machinery...
7027,appeal appeal special leave decision dated feb...,appeal special leave relating industrial dispu...
7028,appeal appeal special leave judgment order dat...,punjab government issued notification sections...
7029,appeal appeal special leave judgment order dat...,respondent district sessions judge erstwhile s...

In [11]:
model_name = 't5-small'
Tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

In [12]:
print(train_df.columns)

Index(['Text', 'Summary'], dtype='object')

In [13]:
max_input_length = 256
max_target_length = 128

def encode(example):
    input_text = 'summarize: ' + example['Text']
    target_text = example['Summary']
    inputs_ids = Tokenizer.encode(
        input_text, max_length = max_input_length, truncation =True
    )
    target_ids = Tokenizer.encode(
        target_text , max_length = max_target_length,truncation = True
    )    
    return {'input_ids':inputs_ids,'labels':target_ids}

train_df = train_df.apply(encode,axis =1)
test_df = test_df.apply(encode,axis =1)

In [14]:
data_collator = DataCollatorForSeq2Seq(tokenizer=Tokenizer, model=model)


training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="no",
    learning_rate=2e-5,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    num_train_epochs=1,
    weight_decay=0.01,
    save_total_limit=1,
    logging_dir="./logs",
    save_strategy="no"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_df,
    eval_dataset=test_df,
    tokenizer=Tokenizer,
    data_collator=data_collator
)

d:\GitUploads\Case-Classification\.venv\lib\site-packages\transformers\training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\lalit\AppData\Local\Temp\ipykernel_9588\3980112742.py:17: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [15]:
trainer.train()

  0%|          | 0/3515 [00:00<?, ?it/s]Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.48.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.
 14%|█▍        | 500/3515 [17:06<1:25:36,  1.70s/it]

{'loss': 5.0622, 'grad_norm': 14.052681922912598, 'learning_rate': 1.7155049786628736e-05, 'epoch': 0.14}

 28%|██▊       | 1000/3515 [31:27<1:08:07,  1.63s/it]

{'loss': 4.6932, 'grad_norm': 3.1709091663360596, 'learning_rate': 1.431009957325747e-05, 'epoch': 0.28}

 43%|████▎     | 1500/3515 [45:08<55:18,  1.65s/it]

{'loss': 4.6472, 'grad_norm': 2.6482927799224854, 'learning_rate': 1.1465149359886204e-05, 'epoch': 0.43}

 57%|█████▋    | 2000/3515 [1:00:06<47:14,  1.87s/it]

{'loss': 4.5934, 'grad_norm': 3.336104393005371, 'learning_rate': 8.620199146514938e-06, 'epoch': 0.57}

 71%|███████   | 2500/3515 [1:15:58<32:35,  1.93s/it]

{'loss': 4.5694, 'grad_norm': 3.3563382625579834, 'learning_rate': 5.77524893314367e-06, 'epoch': 0.71}

 85%|████████▌ | 3000/3515 [1:30:36<14:50,  1.73s/it]

{'loss': 4.4755, 'grad_norm': 3.161313772201538, 'learning_rate': 2.930298719772404e-06, 'epoch': 0.85}

100%|█████████▉| 3500/3515 [1:44:40<00:26,  1.77s/it]

{'loss': 4.5594, 'grad_norm': 2.979816198348999, 'learning_rate': 8.5348506401138e-08, 'epoch': 1.0}

100%|██████████| 3515/3515 [1:45:07<00:00,  1.82s/it]

{'train_runtime': 6307.9844, 'train_samples_per_second': 1.114, 'train_steps_per_second': 0.557, 'train_loss': 4.65688675382568, 'epoch': 1.0}

100%|██████████| 3515/3515 [1:45:08<00:00,  1.79s/it]

TrainOutput(global_step=3515, training_loss=4.65688675382568, metrics={'train_runtime': 6307.9844, 'train_samples_per_second': 1.114, 'train_steps_per_second': 0.557, 'total_flos': 475726432174080.0, 'train_loss': 4.65688675382568, 'epoch': 1.0})

In [16]:
model.save_pretrained("./legal_summarizer_model")
Tokenizer.save_pretrained("./legal_summarizer_model")

('./legal_summarizer_model\\tokenizer_config.json',
 './legal_summarizer_model\\special_tokens_map.json',
 './legal_summarizer_model\\spiece.model',
 './legal_summarizer_model\\added_tokens.json')

In [20]:
ds = load_dataset("ninadn/indian-legal")
test_df = ds['test'].to_pandas()

In [21]:
raw_test_df = test_df
def summarize(text):
    input_ids = Tokenizer.encode("summarize: " + text, return_tensors="pt", max_length=512, truncation=True)
    output = model.generate(input_ids, max_length=128, num_beams=4, early_stopping=True)
    return Tokenizer.decode(output[0], skip_special_tokens=True)

print(summarize(raw_test_df.iloc[0]["Text"]))

appellants who were admittedly displaced persons were granted quasi permanent allotment of 40 standard acres and 15 3/4 units of land in the village of Raikot in 1949. their father Sardar Nand Singh made an application for consolidation of his lands with those of the appellants in the village Raikot.